title: Puzzle Generater Japan

description: >
  タイムインターメディアが提供する、独自AIを搭載したナンプレパズル自動生成エンジン。オープンソースです。

author:
  name: TIMEINTERMEDIA

paginate: 3
paginate_path: page:num

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll-feed
